title: <p align="center"> Rindy Rafida </p>

logo: "/images/logo.jpg?raw=true"

description:
  <p align="center">
  <a href="pdf/CV Rindy Rafida.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/rindy-rafida-51328a206/">LinkedIn</a> |
  <a href="https://github.com/Rindy39">GitHub</a>
  </p>
  
  <p align="justify">
  Fresh Graduate in Statistics from Institut Teknologi Sepuluh Nopember. 
  <br><br>
  I am highly enthusiastic and driven to pursue a career in the fields of Data Analysis or Human Resources. Throughout my academic journey, I possess a consistent work experience in this field. With my skills and expertise, I am committed to delivering excellence in any future where I give my dedication to work.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
