title: Rindy Rafida # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
   I study Statistics at Institut Teknologi Sepuluh Nopember. 
  <br><br>
  Currently, I desire to develop my skills to become a professional statistician. With the abilities that I already have, I will try to give my best wherever my dedication and development are.
  <br><br>
  <a href="pdf/CV RINDY RAFIDA.pdf">Resume</a> 
  <a href="https://www.linkedin.com/in/rindy-rafida/">LinkedIn</a> 
  <a href="https://github.com/Rindy39">Github</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
